version: 0.2

phases:
  install:
    on-failure: ABORT RETRY
    runtime-versions:
      php: 8.2
    commands:
      - echo 'install'
    
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'pre build'
    
  build:
    on-failure: ABORT
    commands:
      - echo 'build'
    
  post_build:
    on-failure: ABORT
    commands:
      - echo 'post build'
